auth:
  secret: ey8fh2j3k4l5m6n7
  expire_time: 3600
  rate_limit: 100/hour
database:
  host: db.example.com
  port: 5432
  credentials:
    user: admin
    password: ${DB_PASSWORD}
logging:
  level: INFO
  format: json
  outputs:
    - stdout
    - /var/log/app.log
metrics:
  enabled: true
  endpoint: /metrics
